// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/tablet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutateRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	RowKey        []byte                 `protobuf:"bytes,2,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	Mutations     []*Mutation            `protobuf:"bytes,3,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowRequest) Reset() {
	*x = MutateRowRequest{}
	mi := &file_proto_tablet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowRequest) ProtoMessage() {}

func (x *MutateRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowRequest.ProtoReflect.Descriptor instead.
func (*MutateRowRequest) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{0}
}

func (x *MutateRowRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *MutateRowRequest) GetRowKey() []byte {
	if x != nil {
		return x.RowKey
	}
	return nil
}

func (x *MutateRowRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type MutateRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRowResponse) Reset() {
	*x = MutateRowResponse{}
	mi := &file_proto_tablet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRowResponse) ProtoMessage() {}

func (x *MutateRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRowResponse.ProtoReflect.Descriptor instead.
func (*MutateRowResponse) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{1}
}

func (x *MutateRowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mutation:
	//
	//	*Mutation_SetCell
	//	*Mutation_DeleteFromColumn
	//	*Mutation_DeleteFromRow
	Mutation      isMutation_Mutation `protobuf_oneof:"mutation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_proto_tablet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{2}
}

func (x *Mutation) GetMutation() isMutation_Mutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *Mutation) GetSetCell() *SetCell {
	if x != nil {
		if x, ok := x.Mutation.(*Mutation_SetCell); ok {
			return x.SetCell
		}
	}
	return nil
}

func (x *Mutation) GetDeleteFromColumn() *DeleteFromColumn {
	if x != nil {
		if x, ok := x.Mutation.(*Mutation_DeleteFromColumn); ok {
			return x.DeleteFromColumn
		}
	}
	return nil
}

func (x *Mutation) GetDeleteFromRow() *DeleteFromRow {
	if x != nil {
		if x, ok := x.Mutation.(*Mutation_DeleteFromRow); ok {
			return x.DeleteFromRow
		}
	}
	return nil
}

type isMutation_Mutation interface {
	isMutation_Mutation()
}

type Mutation_SetCell struct {
	SetCell *SetCell `protobuf:"bytes,1,opt,name=set_cell,json=setCell,proto3,oneof"`
}

type Mutation_DeleteFromColumn struct {
	DeleteFromColumn *DeleteFromColumn `protobuf:"bytes,2,opt,name=delete_from_column,json=deleteFromColumn,proto3,oneof"`
}

type Mutation_DeleteFromRow struct {
	DeleteFromRow *DeleteFromRow `protobuf:"bytes,3,opt,name=delete_from_row,json=deleteFromRow,proto3,oneof"`
}

func (*Mutation_SetCell) isMutation_Mutation() {}

func (*Mutation_DeleteFromColumn) isMutation_Mutation() {}

func (*Mutation_DeleteFromRow) isMutation_Mutation() {}

type SetCell struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FamilyName      string                 `protobuf:"bytes,1,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	ColumnQualifier []byte                 `protobuf:"bytes,2,opt,name=column_qualifier,json=columnQualifier,proto3" json:"column_qualifier,omitempty"`
	TimestampMicros int64                  `protobuf:"varint,3,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"` // -1 for "now"
	Value           []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetCell) Reset() {
	*x = SetCell{}
	mi := &file_proto_tablet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCell) ProtoMessage() {}

func (x *SetCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCell.ProtoReflect.Descriptor instead.
func (*SetCell) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{3}
}

func (x *SetCell) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *SetCell) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

func (x *SetCell) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *SetCell) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteFromColumn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FamilyName      string                 `protobuf:"bytes,1,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	ColumnQualifier []byte                 `protobuf:"bytes,2,opt,name=column_qualifier,json=columnQualifier,proto3" json:"column_qualifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteFromColumn) Reset() {
	*x = DeleteFromColumn{}
	mi := &file_proto_tablet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFromColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFromColumn) ProtoMessage() {}

func (x *DeleteFromColumn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFromColumn.ProtoReflect.Descriptor instead.
func (*DeleteFromColumn) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFromColumn) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *DeleteFromColumn) GetColumnQualifier() []byte {
	if x != nil {
		return x.ColumnQualifier
	}
	return nil
}

type DeleteFromRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFromRow) Reset() {
	*x = DeleteFromRow{}
	mi := &file_proto_tablet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFromRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFromRow) ProtoMessage() {}

func (x *DeleteFromRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFromRow.ProtoReflect.Descriptor instead.
func (*DeleteFromRow) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{5}
}

type ReadRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	StartRowKey   []byte                 `protobuf:"bytes,2,opt,name=start_row_key,json=startRowKey,proto3" json:"start_row_key,omitempty"`
	EndRowKey     []byte                 `protobuf:"bytes,3,opt,name=end_row_key,json=endRowKey,proto3" json:"end_row_key,omitempty"`
	LimitRows     int32                  `protobuf:"varint,4,opt,name=limit_rows,json=limitRows,proto3" json:"limit_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsRequest) Reset() {
	*x = ReadRowsRequest{}
	mi := &file_proto_tablet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsRequest) ProtoMessage() {}

func (x *ReadRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsRequest.ProtoReflect.Descriptor instead.
func (*ReadRowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRowsRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ReadRowsRequest) GetStartRowKey() []byte {
	if x != nil {
		return x.StartRowKey
	}
	return nil
}

func (x *ReadRowsRequest) GetEndRowKey() []byte {
	if x != nil {
		return x.EndRowKey
	}
	return nil
}

func (x *ReadRowsRequest) GetLimitRows() int32 {
	if x != nil {
		return x.LimitRows
	}
	return 0
}

type ReadRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *Row                   `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsResponse) Reset() {
	*x = ReadRowsResponse{}
	mi := &file_proto_tablet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsResponse) ProtoMessage() {}

func (x *ReadRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsResponse.ProtoReflect.Descriptor instead.
func (*ReadRowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRowsResponse) GetRow() *Row {
	if x != nil {
		return x.Row
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Families      []*Family              `protobuf:"bytes,2,rep,name=families,proto3" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_tablet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{8}
}

func (x *Row) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Row) GetFamilies() []*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

type Family struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*Column              `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_proto_tablet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{9}
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qualifier     []byte                 `protobuf:"bytes,1,opt,name=qualifier,proto3" json:"qualifier,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_proto_tablet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{10}
}

func (x *Column) GetQualifier() []byte {
	if x != nil {
		return x.Qualifier
	}
	return nil
}

func (x *Column) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Cell struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampMicros int64                  `protobuf:"varint,1,opt,name=timestamp_micros,json=timestampMicros,proto3" json:"timestamp_micros,omitempty"`
	Value           []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_proto_tablet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tablet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_proto_tablet_proto_rawDescGZIP(), []int{11}
}

func (x *Cell) GetTimestampMicros() int64 {
	if x != nil {
		return x.TimestampMicros
	}
	return 0
}

func (x *Cell) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_tablet_proto protoreflect.FileDescriptor

const file_proto_tablet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tablet.proto\x12\ftabletserver\"\x80\x01\n" +
	"\x10MutateRowRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x17\n" +
	"\arow_key\x18\x02 \x01(\fR\x06rowKey\x124\n" +
	"\tmutations\x18\x03 \x03(\v2\x16.tabletserver.MutationR\tmutations\"-\n" +
	"\x11MutateRowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe1\x01\n" +
	"\bMutation\x122\n" +
	"\bset_cell\x18\x01 \x01(\v2\x15.tabletserver.SetCellH\x00R\asetCell\x12N\n" +
	"\x12delete_from_column\x18\x02 \x01(\v2\x1e.tabletserver.DeleteFromColumnH\x00R\x10deleteFromColumn\x12E\n" +
	"\x0fdelete_from_row\x18\x03 \x01(\v2\x1b.tabletserver.DeleteFromRowH\x00R\rdeleteFromRowB\n" +
	"\n" +
	"\bmutation\"\x96\x01\n" +
	"\aSetCell\x12\x1f\n" +
	"\vfamily_name\x18\x01 \x01(\tR\n" +
	"familyName\x12)\n" +
	"\x10column_qualifier\x18\x02 \x01(\fR\x0fcolumnQualifier\x12)\n" +
	"\x10timestamp_micros\x18\x03 \x01(\x03R\x0ftimestampMicros\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"^\n" +
	"\x10DeleteFromColumn\x12\x1f\n" +
	"\vfamily_name\x18\x01 \x01(\tR\n" +
	"familyName\x12)\n" +
	"\x10column_qualifier\x18\x02 \x01(\fR\x0fcolumnQualifier\"\x0f\n" +
	"\rDeleteFromRow\"\x93\x01\n" +
	"\x0fReadRowsRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\"\n" +
	"\rstart_row_key\x18\x02 \x01(\fR\vstartRowKey\x12\x1e\n" +
	"\vend_row_key\x18\x03 \x01(\fR\tendRowKey\x12\x1d\n" +
	"\n" +
	"limit_rows\x18\x04 \x01(\x05R\tlimitRows\"7\n" +
	"\x10ReadRowsResponse\x12#\n" +
	"\x03row\x18\x01 \x01(\v2\x11.tabletserver.RowR\x03row\"I\n" +
	"\x03Row\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x120\n" +
	"\bfamilies\x18\x02 \x03(\v2\x14.tabletserver.FamilyR\bfamilies\"L\n" +
	"\x06Family\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\acolumns\x18\x02 \x03(\v2\x14.tabletserver.ColumnR\acolumns\"P\n" +
	"\x06Column\x12\x1c\n" +
	"\tqualifier\x18\x01 \x01(\fR\tqualifier\x12(\n" +
	"\x05cells\x18\x02 \x03(\v2\x12.tabletserver.CellR\x05cells\"G\n" +
	"\x04Cell\x12)\n" +
	"\x10timestamp_micros\x18\x01 \x01(\x03R\x0ftimestampMicros\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\xa9\x01\n" +
	"\fTabletServer\x12L\n" +
	"\tMutateRow\x12\x1e.tabletserver.MutateRowRequest\x1a\x1f.tabletserver.MutateRowResponse\x12K\n" +
	"\bReadRows\x12\x1d.tabletserver.ReadRowsRequest\x1a\x1e.tabletserver.ReadRowsResponse0\x01B*Z(github.com/pancakeshack/toy-big-table/pbb\x06proto3"

var (
	file_proto_tablet_proto_rawDescOnce sync.Once
	file_proto_tablet_proto_rawDescData []byte
)

func file_proto_tablet_proto_rawDescGZIP() []byte {
	file_proto_tablet_proto_rawDescOnce.Do(func() {
		file_proto_tablet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tablet_proto_rawDesc), len(file_proto_tablet_proto_rawDesc)))
	})
	return file_proto_tablet_proto_rawDescData
}

var file_proto_tablet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_tablet_proto_goTypes = []any{
	(*MutateRowRequest)(nil),  // 0: tabletserver.MutateRowRequest
	(*MutateRowResponse)(nil), // 1: tabletserver.MutateRowResponse
	(*Mutation)(nil),          // 2: tabletserver.Mutation
	(*SetCell)(nil),           // 3: tabletserver.SetCell
	(*DeleteFromColumn)(nil),  // 4: tabletserver.DeleteFromColumn
	(*DeleteFromRow)(nil),     // 5: tabletserver.DeleteFromRow
	(*ReadRowsRequest)(nil),   // 6: tabletserver.ReadRowsRequest
	(*ReadRowsResponse)(nil),  // 7: tabletserver.ReadRowsResponse
	(*Row)(nil),               // 8: tabletserver.Row
	(*Family)(nil),            // 9: tabletserver.Family
	(*Column)(nil),            // 10: tabletserver.Column
	(*Cell)(nil),              // 11: tabletserver.Cell
}
var file_proto_tablet_proto_depIdxs = []int32{
	2,  // 0: tabletserver.MutateRowRequest.mutations:type_name -> tabletserver.Mutation
	3,  // 1: tabletserver.Mutation.set_cell:type_name -> tabletserver.SetCell
	4,  // 2: tabletserver.Mutation.delete_from_column:type_name -> tabletserver.DeleteFromColumn
	5,  // 3: tabletserver.Mutation.delete_from_row:type_name -> tabletserver.DeleteFromRow
	8,  // 4: tabletserver.ReadRowsResponse.row:type_name -> tabletserver.Row
	9,  // 5: tabletserver.Row.families:type_name -> tabletserver.Family
	10, // 6: tabletserver.Family.columns:type_name -> tabletserver.Column
	11, // 7: tabletserver.Column.cells:type_name -> tabletserver.Cell
	0,  // 8: tabletserver.TabletServer.MutateRow:input_type -> tabletserver.MutateRowRequest
	6,  // 9: tabletserver.TabletServer.ReadRows:input_type -> tabletserver.ReadRowsRequest
	1,  // 10: tabletserver.TabletServer.MutateRow:output_type -> tabletserver.MutateRowResponse
	7,  // 11: tabletserver.TabletServer.ReadRows:output_type -> tabletserver.ReadRowsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_tablet_proto_init() }
func file_proto_tablet_proto_init() {
	if File_proto_tablet_proto != nil {
		return
	}
	file_proto_tablet_proto_msgTypes[2].OneofWrappers = []any{
		(*Mutation_SetCell)(nil),
		(*Mutation_DeleteFromColumn)(nil),
		(*Mutation_DeleteFromRow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tablet_proto_rawDesc), len(file_proto_tablet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tablet_proto_goTypes,
		DependencyIndexes: file_proto_tablet_proto_depIdxs,
		MessageInfos:      file_proto_tablet_proto_msgTypes,
	}.Build()
	File_proto_tablet_proto = out.File
	file_proto_tablet_proto_goTypes = nil
	file_proto_tablet_proto_depIdxs = nil
}
