// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/tablet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TabletServer_MutateRow_FullMethodName = "/tabletserver.TabletServer/MutateRow"
	TabletServer_ReadRows_FullMethodName  = "/tabletserver.TabletServer/ReadRows"
)

// TabletServerClient is the client API for TabletServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TabletServerClient interface {
	MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResponse, error)
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error)
}

type tabletServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTabletServerClient(cc grpc.ClientConnInterface) TabletServerClient {
	return &tabletServerClient{cc}
}

func (c *tabletServerClient) MutateRow(ctx context.Context, in *MutateRowRequest, opts ...grpc.CallOption) (*MutateRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateRowResponse)
	err := c.cc.Invoke(ctx, TabletServer_MutateRow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabletServerClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TabletServer_ServiceDesc.Streams[0], TabletServer_ReadRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRowsRequest, ReadRowsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TabletServer_ReadRowsClient = grpc.ServerStreamingClient[ReadRowsResponse]

// TabletServerServer is the server API for TabletServer service.
// All implementations must embed UnimplementedTabletServerServer
// for forward compatibility.
type TabletServerServer interface {
	MutateRow(context.Context, *MutateRowRequest) (*MutateRowResponse, error)
	ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error
	mustEmbedUnimplementedTabletServerServer()
}

// UnimplementedTabletServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTabletServerServer struct{}

func (UnimplementedTabletServerServer) MutateRow(context.Context, *MutateRowRequest) (*MutateRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MutateRow not implemented")
}
func (UnimplementedTabletServerServer) ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadRows not implemented")
}
func (UnimplementedTabletServerServer) mustEmbedUnimplementedTabletServerServer() {}
func (UnimplementedTabletServerServer) testEmbeddedByValue()                      {}

// UnsafeTabletServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TabletServerServer will
// result in compilation errors.
type UnsafeTabletServerServer interface {
	mustEmbedUnimplementedTabletServerServer()
}

func RegisterTabletServerServer(s grpc.ServiceRegistrar, srv TabletServerServer) {
	// If the following call panics, it indicates UnimplementedTabletServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TabletServer_ServiceDesc, srv)
}

func _TabletServer_MutateRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServerServer).MutateRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabletServer_MutateRow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServerServer).MutateRow(ctx, req.(*MutateRowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabletServer_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TabletServerServer).ReadRows(m, &grpc.GenericServerStream[ReadRowsRequest, ReadRowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TabletServer_ReadRowsServer = grpc.ServerStreamingServer[ReadRowsResponse]

// TabletServer_ServiceDesc is the grpc.ServiceDesc for TabletServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TabletServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tabletserver.TabletServer",
	HandlerType: (*TabletServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateRow",
			Handler:    _TabletServer_MutateRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _TabletServer_ReadRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tablet.proto",
}
